name: eseminars_mobile
description: "A new Flutter project."
publish_to: 'none' # Sprečava slučajno objavljivanje na pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  provider: ^6.1.4
  build: ^2.4.1
  awesome_dialog: ^3.2.1
  iconsax_flutter: ^1.0.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Mjesto za dodavanje fontova, ako zatreba
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
